// Code generated by gogs. DO NOT EDIT.
package server

import (
	"context"

	"github.com/szpnygo/gowebrtc-signal/internal/logic/baseworld"
	"github.com/szpnygo/gowebrtc-signal/model"

	"github.com/metagogs/gogs/session"
	"github.com/szpnygo/gowebrtc-signal/internal/svc"
)

type Server struct {
	svcCtx *svc.ServiceContext
}

func NewServer(svcCtx *svc.ServiceContext) *Server {
	return &Server{
		svcCtx: svcCtx,
	}
}

func (gogs *Server) BindUser(ctx context.Context, s *session.Session, in *model.BindUser) {
	l := baseworld.NewBindUserLogic(ctx, gogs.svcCtx, s)
	l.Handler(in)
}

func (gogs *Server) OutgoingMessage(ctx context.Context, s *session.Session, in *model.OutgoingMessage) {
	l := baseworld.NewOutgoingMessageLogic(ctx, gogs.svcCtx, s)
	l.Handler(in)
}
